# Generated by Django 5.0.4 on 2024-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment_label',
            field=models.CharField(max_length=20),
        ),
    ]
